services:
  challenge:
    build: ./service/app
    ports:
      - "31001:31001"
    depends_on:
      - admin-bot
    environment:
      - ADMIN_HOST=admin-bot
      - ADMIN_PORT=3001

  admin-bot:
    build: ./service/bot
    environment:
      - BASE_URL=http://challenge:31001/
      - FLAG=grey{fake_flag_for_testing}