services:
 web:
    build: ./app
    ports:
      - 30080:8080
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "1"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      FLASK_SECRET_KEY: s7d9sa6D234bk23bt
      ADMIN_HOST: admin-bot
      ADMIN_PORT: 3001
    volumes:
      - ./app:/app
    depends_on:
      - db
    restart: unless-stopped

 db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

 admin-bot:
    build: ./admin
    environment:
      - BASE_URL=http://web:8080/
      - FLAG=grey{this_is_the_admin_session_cookie}
      - MASTER_SECRET=super_secret_key_123
    restart: unless-stopped
    init: true  # prevent puppeteer from using pid 1 so zombie proc can be reaped

 internal:
    build: ./internal
    environment:
      - FLAG=grey{this_is_an_internal_secret}

    restart: unless-stopped
